"""
Populate the database with sample data for local development/testing.

Usage:
    python seed.py
"""
from datetime import datetime, timedelta
import random

from app import create_app
from app.extensions import db
from app.models import User, Profile, Category, Tag, Blog, Comment, Like, Bookmark, Follower

CATEGORIES = [
    ("Technology", "💻"), ("Programming", "⌨️"), ("AI", "🤖"), ("Travel", "✈️"),
    ("Food", "🍜"), ("Lifestyle", "🌿"), ("Finance", "💰"), ("Education", "📚"),
]

TAGS = ["react", "python", "flask", "design", "productivity", "security", "career", "opensource"]

TITLES = [
    "Designing Interfaces That Feel Alive",
    "The Quiet Art of Debugging",
    "Why Minimalism Wins in Product Design",
    "A Backpacker's Guide to the Himalayas",
    "Building a Design System From Scratch",
    "How I Cracked My First CTF Challenge",
    "The Case for Boring Technology",
    "React Server Components, Explained Simply",
    "Understanding XSS Through a Real Exploit",
    "Notes on Writing Every Single Day",
]

SAMPLE_CONTENT = """## Introduction

This is a sample post generated by the seed script so the API has
realistic-looking data to serve to the front end during development.

## The core idea

Replace this content by creating real posts through POST /api/blogs
once you've logged in and grabbed a JWT access token.

```python
def hello():
    return "Inkwell API is running"
```

## Closing thoughts

Happy building!
"""


def run():
    app = create_app()
    with app.app_context():
        db.drop_all()
        db.create_all()

        # Users
        users = []
        for i, (name, email) in enumerate([
            ("Lavanya Sharma", "lavanya@example.com"),
            ("Ananya Rao", "ananya@example.com"),
            ("Rohit Verma", "rohit@example.com"),
            ("Meera Iyer", "meera@example.com"),
        ]):
            u = User(name=name, email=email, is_verified=True)
            u.set_password("password123")
            db.session.add(u)
            db.session.flush()
            db.session.add(Profile(user_id=u.id, bio=f"Hi, I'm {name.split()[0]}.", github=name.split()[0].lower()))
            users.append(u)

        # Categories
        categories = []
        for name, icon in CATEGORIES:
            c = Category(name=name, slug=name.lower(), icon=icon)
            db.session.add(c)
            categories.append(c)

        # Tags
        tags = []
        for t in TAGS:
            tag = Tag(name=t, slug=t)
            db.session.add(tag)
            tags.append(tag)

        db.session.flush()

        # Blogs
        blogs = []
        for i, title in enumerate(TITLES):
            author = users[i % len(users)]
            category = categories[i % len(categories)]
            blog = Blog(
                title=title,
                slug=title.lower().replace(" ", "-").replace(",", "").replace("'", ""),
                content=SAMPLE_CONTENT,
                excerpt="A closer look at the ideas, tradeoffs, and small decisions that add up to something worth reading.",
                status="published",
                author_id=author.id,
                category_id=category.id,
                views=random.randint(400, 9000),
                reading_time=random.randint(3, 9),
                is_featured=(i % 4 == 0),
                created_at=datetime.utcnow() - timedelta(days=i),
                published_at=datetime.utcnow() - timedelta(days=i),
            )
            blog.tags = random.sample(tags, k=3)
            db.session.add(blog)
            blogs.append(blog)

        db.session.flush()

        # A couple of drafts for the first user (shows up on their dashboard)
        db.session.add(Blog(
            title="Untitled draft about async Python",
            slug="untitled-draft-about-async-python",
            content="Just getting started...",
            excerpt="Just getting started...",
            status="draft",
            author_id=users[0].id,
            category_id=categories[1].id,
        ))

        # Comments, likes, bookmarks, follows
        for blog in blogs[:6]:
            for commenter in random.sample(users, k=2):
                db.session.add(Comment(blog_id=blog.id, author_id=commenter.id, content="Really enjoyed this — great points."))
            for liker in random.sample(users, k=random.randint(1, 3)):
                db.session.add(Like(user_id=liker.id, blog_id=blog.id))
            db.session.add(Bookmark(user_id=users[0].id, blog_id=blog.id))

        db.session.add(Follower(follower_id=users[1].id, followee_id=users[0].id))
        db.session.add(Follower(follower_id=users[2].id, followee_id=users[0].id))

        db.session.commit()
        print("✅ Seeded database with sample users, blogs, comments, likes, and bookmarks.")
        print("   Sample login: lavanya@example.com / password123")


if __name__ == "__main__":
    run()
